version: '3.8'

services:
  mysql_databse:
    build:
      context: .
      dockerfile: database.Dockerfile
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - ../environment/.env
